name: CI

on:
  push:
    branches:
      - 'master'
    paths:
      - '**/container-module-federation'
    # nosso repo tem varias pastas e  diretórios
    #aqui garanto que ci/cd vai rodar separado

  #quando coloco defaults significa que vou trabalhar nesse direito
  #github e inteligente de mudar para esse cenário nao preciso usar cd container-module-federation
defaults:
  run:
    working-directory: '**/container-module-federation'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      #https://github.com/chrislennon/action-aws-cli
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Prepared node js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: node --version
      - run: npm install
      - run: npm run build
      #  a partir do run permite usar o uses como dicionario
      # - uses
      - uses: chrislennon/action-aws-cli@v1.1
      # dist e aonde gerado o build
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET }}/container/latest
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }}  --paths '/container/latest/index.html'
